version: '3.5'
services:
  grpc:
    container_name: cpp-grpc
    build: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - "3000:50051"
    stdin_open: true
    tty: true
